# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b3c50361e93c5788295de001c30cadf2e9ee90e1aef6ae4190337cf8bf5377bb91454206255b5909fb17faab38eacdad4e2a665dde53c9d27a1e07088309072

test:
  secret_key_base: 9b850daf943bd53b31d6f147f8b5d9f6a59224e9e3a7b9e1aa90c11ddfbe0285cfc40e398ee13bcf6d02ead8be817a850234fa4f34acb8a678264b47fd785386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
